### ISSUE TITLE
MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by Wolf-Quiteque** [hyobyun/exchangeengine#2]
I GET THIS ERROR WHEN RUNNING **NPM TEST**, any suggestion?:

Error: Cannot find module 'C:\Users\user\Documents\wolf\code\exchangeengine\node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by behzad-ahmadi** [comment]
I have the same problem as @Wolf-Quiteque seaid.
Any solution?

**Comment by ARYAN7599** [comment]
Same Problem with me.....
Any Solutions ?
